title       = "codecademy"
baseURL     = "https://codecademy-cli.tamnd.com/"
description = "A command line for codecademy."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/codecademy-cli"
